spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/xmlpayload
    username: postgres
    password: Aai@8530

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 2025